import { Product } from '../app/model/product.model';

export const PRODUCTS: Product[] = [
  {
    "id": "8915ea51-4650-497f-b7ae-3a08231933eb",
    "name": "Apple iPhone X",
    "unitPrice": 999,
    "descriptionShort": "Мы знаем что ты его хочешь",
    "descriptionLong": "Мы всегда мечтали сделать iPhone одним большим дисплеем. Настолько впечатляющим дисплеем, чтобы вы забывали о самом физическом устройстве. И настолько умным устройством, чтобы оно реагировало на прикосновение, слово и даже взгляд. iPhone X воплощает мечту в реальность. Это смартфон будущего.",
    "unitsInStock": 1,
    "imageName": "compare_iphoneX_silver_large.jpg",
    "length": 143.6,
    "width": 70.9,
    "thickness": 7.7,
    "weight": 174,
    "display": "Полноэкранный дисплей OLED Multi‑Touch",
    "displaySize": 5.8,
    "resolutionHeight": 2436,
    "resolutionWidth": 1125
  },
  {
    "id": "6be1377b-b144-4219-90ae-5431b96e7ca6",
    "name": "Apple iPhone 8 Plus",
    "unitPrice": 799,
    "descriptionShort": "Когда не хватило на iPhone X",
    "descriptionLong": "Для iPhone 8 мы разработали совершенно новый дизайн, в котором передняя и задняя панели выполнены из стекла. Самая популярная камера усовершенствована. Установлен самый умный и мощный процессор, когда-﻿либо созданный для iPhone. Без проводов процесс зарядки становится элементарным. А дополненная реальность открывает невиданные до сих пор возможности. iPhone 8. Новое поколение iPhone.",
    "unitsInStock": 3,
    "imageName": "compare_iphone8plus_silver_large.jpg",
    "length": 158.4,
    "width": 78.1,
    "thickness": 7.5,
    "weight": 202,
    "display": "Широко­форматный ЖК‑дисплей Multi‑Touch",
    "displaySize": 5.5,
    "resolutionHeight": 1920,
    "resolutionWidth": 1080
  },
  {
    "id": "d2720e91-3ded-49e1-b684-273b0af50fda",
    "name": "Apple iPhone 8",
    "unitPrice": 699,
    "descriptionShort": "За такие деньги - спасибо что хоть iPhone",
    "descriptionLong": "Для iPhone 8 мы разработали совершенно новый дизайн, в котором передняя и задняя панели выполнены из стекла. Самая популярная камера усовершенствована. Установлен самый умный и мощный процессор, когда-﻿либо созданный для iPhone. Без проводов процесс зарядки становится элементарным. А дополненная реальность открывает невиданные до сих пор возможности. iPhone 8. Новое поколение iPhone.",
    "unitsInStock": 15,
    "imageName": "compare_iphone8_silver_large.jpg",
    "length": 138.4,
    "width": 67.3,
    "thickness": 7.3,
    "weight": 148,
    "display": "Широко­форматный ЖК‑дисплей Multi‑Touch",
    "displaySize": 4.7,
    "resolutionHeight": 1334,
    "resolutionWidth": 750
  },
  {
    "id": "26ba4317-3751-4863-a760-3d22828554f5",
    "name": "Samsung Galaxy S8",
    "unitPrice": 424,
    "descriptionShort": "Великолепный и безграничный",
    "descriptionLong": "Samsung Galaxy S8 переворачивают представление о классическом дизайне смартфона. Безграничный* изогнутый с двух сторон экран подчеркивает гармонию стиля и инноваций.",
    "unitsInStock": 0,
    "imageName": "samsung-galaxy-s8-gold.png",
    "length": 148.9,
    "width": 68.1,
    "thickness": 8.0,
    "weight": 155,
    "display": "Изогнутый с двух сторон Super AMOLED",
    "displaySize": 5.8,
    "resolutionHeight": 2960,
    "resolutionWidth": 1440
  },
  {
    "id": "79e75010-88f6-427c-8259-899d37b209b2",
    "name": "Samsung Galaxy Note 8",
    "unitPrice": 929,
    "descriptionShort": "Добивайся большего",
    "descriptionLong": "Возможность увидеть больше и общаться по-новому. Добивайся большего с Galaxy Note8! Экран Galaxy Note8 с диагональю 6,3 – больше пространства для новых возможностей. Он стал еще больше, но по-прежнему легко помещается в руке.",
    "unitsInStock": 5,
    "imageName": "galaxy_note_8_zoom_comp.png",
    "length": 162.5,
    "width": 74.8,
    "thickness": 8.6,
    "weight": 195,
    "display": "Изогнутый с двух сторон Super AMOLED",
    "displaySize": 6.3,
    "resolutionHeight": 2960,
    "resolutionWidth": 1440
  }
];
